apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins-msarch.fullname" . }}
  labels:
    {{- include "jenkins-msarch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins-msarch.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "jenkins-msarch.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.master.securityContext | nindent 10 }}
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 300
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /login
              port: http
            failureThreshold: 6
            initialDelaySeconds: 180
            periodSeconds: 10
          env:
            - name: JAVA_OPTS
              value: "-Djenkins-msarch.install.runSetupWizard=false"
      volumes:
        - name: jenkins-home
          emptyDir: {}
