apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins-msarch.fullname" . }}-slave-2
  labels:
    {{- include "jenkins-msarch.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "jenkins-msarch.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "jenkins-msarch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: jenkins-slave
          image: jenkins/jenkins:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JENKINS_URL
              value: "127.0.0.1:8080"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: workspace-volume
              mountPath: /home/jenkins/agent

      volumes:
        - name: workspace-volume
          emptyDir: {}


